
runtime: python|3.8  # Define the runtime version
env: flex             # Azure's flexible environment

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker web_app:app

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
